name: Angular CI
on: [push]

jobs:
  angular-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: node
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: LS
        run: ls -al
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: latest
      - name: Setup Angular
        run: |
          npm install -g @angular/cli -y
          ng version
      - name: Install dependencies
        run: |
          cd githubactions
          npm i
      - name: run tests
        run: |
          cd githubactions
          npm run test
